worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 8282;
        server_name _;

        root /usr/share/nginx/html;
        index ip-manager.html;

        location / {
            try_files $uri /ip-manager.html;
        }

        location /api/ {
            proxy_pass http://json-server:18281/;
            proxy_set_header Host $host;
        }
    }
}
